# Generated by Django 4.2.3 on 2024-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=100)),
                ('recipeDescrip', models.TextField()),
                ('recipeImg', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
