# Generated by Django 4.2.3 on 2024-02-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApi', '0002_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
